import assert from 'node:assert/strict';
import {registerHooks} from 'node:module';
import {mkdtemp,readFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createClient} from '@libsql/client';
registerHooks({resolve(specifier,context,next){try{return next(specifier,context);}catch(error){if(specifier.startsWith('.'))return next(`${specifier}.ts`,context);throw error;}}});
const directory=await mkdtemp(join(tmpdir(),'mirana-research-jobs-'));
const keys=['TURSO_DATABASE_URL','TURSO_AUTH_TOKEN','NODE_ENV','RESEARCH_MAX_CALLS','RESEARCH_MAX_TOOL_CALLS','RESEARCH_MAX_ROUNDS','RESEARCH_MAX_INPUT_TOKENS','RESEARCH_MAX_OUTPUT_TOKENS','RESEARCH_USER_DAILY_JOB_LIMIT','RESEARCH_DAILY_JOB_LIMIT','RESEARCH_RETRY_JOB_ID','RESEARCH_RETRY_OUTPUT_BUDGET'];
const saved=Object.fromEntries(keys.map(k=>[k,process.env[k]]));
let client;
try {
  process.env.TURSO_DATABASE_URL=`file:${join(directory,'isolated.db')}`;delete process.env.TURSO_AUTH_TOKEN;process.env.NODE_ENV='test';delete process.env.RESEARCH_MAX_CALLS;delete process.env.RESEARCH_MAX_TOOL_CALLS;delete process.env.RESEARCH_MAX_ROUNDS;delete process.env.RESEARCH_MAX_INPUT_TOKENS;delete process.env.RESEARCH_MAX_OUTPUT_TOKENS;
  const {databaseClient}=await import('../lib/database.ts');client=databaseClient();
  const ddl=await readFile(new URL('../db/schema.sql',import.meta.url),'utf8');await client.batch(ddl.split(';').map(s=>s.trim()).filter(s=>s&&!s.includes('research_jobs')),'write');
  const jobs=await import('../lib/research-jobs.ts');
  const brief={requestText:'A quiet reliable air purifier',budget:20000,topN:3,customTags:['Quiet'],postcode:'600019',alerts:{enabled:false},parsed:{category:'Home'}};
  const insert=async(id,user='owner',b=brief)=>client.execute({sql:'INSERT INTO purchases (id,user_id,brief,status,updated_at) VALUES (?,?,?,?,?)',args:[id,user,JSON.stringify(b),'queued',new Date().toISOString()]});
  const edit=async(id,b,status='queued')=>client.execute({sql:'UPDATE purchases SET brief=?,status=?,updated_at=? WHERE id=?',args:[JSON.stringify(b),status,new Date().toISOString(),id]});
  await insert('a');await insert('b','other');
  const job=await jobs.ensureResearchJob('a','owner');assert.equal(job.briefRevision,0);assert.equal(job.purchase.alerts,undefined);assert.equal(job.purchase.parsed,undefined);
  assert.equal((await jobs.ensureResearchJob('a','owner')).id,job.id);
  assert.equal(await jobs.getResearchJob('a','other'),null);await assert.rejects(jobs.ensureResearchJob('a','other'),/not found/);
  assert.equal(jobs.researchBriefHash({...brief,alerts:{enabled:true},parsed:null,retryAt:'later'}),jobs.researchBriefHash(brief));
  assert.equal(jobs.researchBriefHash({...brief,customTags:['Different']} )===jobs.researchBriefHash(brief),false);
  const [first,second]=await Promise.all([jobs.claimResearchJob(job.id),jobs.claimResearchJob(job.id)]);assert.equal([first,second].filter(Boolean).length,1);
  const claim=first||second;
  await jobs.reserveResearchCall(job.id,claim.token);
  const plan={criteria:['Quiet','New only'],questions:['Filter availability'],rawProviderBody:'must remain server-side'};
  await jobs.completeResearchStep(job.id,claim.token,'plan',plan,'gather','provider secret',{inputTokens:10,outputTokens:20});
  await jobs.completeResearchStep(job.id,claim.token,'plan',plan,'gather','repeat',{inputTokens:10,outputTokens:20});
  let view=await jobs.getResearchJob('a','owner');assert.equal(view.stage,'gather');assert.equal(view.limits.attemptedCalls,1);assert.equal(JSON.stringify(view).includes('rawProviderBody'),false);assert.equal(JSON.stringify(view).includes('provider secret'),false);
  await edit('a',{...brief,alerts:{enabled:true}});assert.equal((await jobs.assertResearchJobCurrent(job.id,claim.token)).stage,'gather');
  // Simulate crash after reserving a billable call: reclaim counts it and retains completed steps.
  await jobs.reserveResearchCall(job.id,claim.token);
  await client.execute({sql:'UPDATE research_jobs SET lease_expires=? WHERE id=?',args:[Date.now()-1,job.id]});
  await assert.rejects(jobs.completeResearchStep(job.id,claim.token,'gather',{},'assess'),/lease/);
  const reclaimed=await jobs.claimResearchJob(job.id);assert.ok(reclaimed);assert.notEqual(reclaimed.token,claim.token);assert.deepEqual(reclaimed.job.outputs.plan,plan);assert.equal(reclaimed.job.attemptedCalls,2);assert.equal(reclaimed.job.inputTokens,10);
  await assert.rejects(jobs.releaseResearchJob(job.id,claim.token),/lease/);
  const observer=createClient({url:process.env.TURSO_DATABASE_URL});try{const row=(await observer.execute({sql:'SELECT payload FROM research_jobs WHERE id=?',args:[job.id]})).rows[0];assert.deepEqual(JSON.parse(row.payload).outputs.plan,plan);}finally{observer.close();}
  await jobs.completeResearchStep(job.id,reclaimed.token,'gather',{sources:[]},'assess');
  await jobs.completeResearchStep(job.id,reclaimed.token,'assess',{gaps:['Price']},'followup');
  let followed=await jobs.completeResearchStep(job.id,reclaimed.token,'followup',{round:1,sources:['a']},'assess');assert.equal(followed.rounds,1);assert.equal(followed.outputs.followup.length,1);
  await jobs.completeResearchStep(job.id,reclaimed.token,'assess',{gaps:['Stock']},'followup');
  followed=await jobs.completeResearchStep(job.id,reclaimed.token,'followup',{round:2,sources:['b']},'assess');assert.equal(followed.rounds,2);assert.equal(followed.outputs.followup.length,2);
  await jobs.failResearchJob(job.id,reclaimed.token,'raw provider sensitive error',{retryable:true,retryAt:new Date(Date.now()+60000).toISOString()});
  assert.equal((await jobs.listRunnableResearchJobs({purchaseId:'a'})).length,0);assert.equal(await jobs.claimResearchJob(job.id),null);
  view=await jobs.retryResearchJob('a','owner');assert.equal(view.stage,'assess');assert.equal(view.limits.attemptedCalls,2);assert.equal(view.rounds,2);
  const retry=await jobs.claimResearchJob(job.id);await jobs.completeResearchStep(job.id,retry.token,'assess',{gaps:[]},'followup');await assert.rejects(jobs.completeResearchStep(job.id,retry.token,'followup',{},'assess'),/follow-up limit/);
  await jobs.releaseResearchJob(job.id,retry.token);
  await edit('a',{...brief,briefRevision:1,budget:15000});const revised=await jobs.ensureResearchJob('a','owner');assert.notEqual(revised.id,job.id);assert.equal(await jobs.claimResearchJob(job.id),null);
  const revisedClaim=await jobs.claimResearchJob(revised.id);await edit('a',{...brief,briefRevision:1,budget:15000},'paused');await assert.rejects(jobs.assertResearchJobCurrent(revised.id,revisedClaim.token),/cancelled/);assert.equal((await jobs.getResearchJob('a','owner')).status,'cancelled');
  await assert.rejects(jobs.retryResearchJob('a','owner'),/Resume/);await edit('a',{...brief,briefRevision:1,budget:15000});await jobs.retryResearchJob('a','owner');
  const resumed=await jobs.claimResearchJob(revised.id);await edit('a',{...brief,briefRevision:2,budget:14000});await assert.rejects(jobs.assertResearchJobCurrent(revised.id,resumed.token),/superseded/);
  const third=await jobs.ensureResearchJob('a','owner'),thirdClaim=await jobs.claimResearchJob(third.id);await edit('a',{...brief,briefRevision:2,budget:14000},'bought');await assert.rejects(jobs.finishResearchJob(third.id,thirdClaim.token),/cancelled/);
  await assert.rejects(jobs.cancelResearchJob('a','other'),/not found/);
  const budget=await jobs.ensureResearchJob('b','other'),budgetClaim=await jobs.claimResearchJob(budget.id);for(let i=0;i<8;i++)await jobs.reserveResearchCall(budget.id,budgetClaim.token);await assert.rejects(jobs.reserveResearchCall(budget.id,budgetClaim.token),/budget/);await jobs.failResearchJob(budget.id,budgetClaim.token,'limited');await assert.rejects(jobs.retryResearchJob('b','other'),/budget/);
  await insert('publish');const pub=await jobs.ensureResearchJob('publish','owner');const pubClaim=await jobs.claimResearchJob(pub.id);
  for(const [stage,next] of [['plan','gather'],['gather','assess'],['assess','synthesize'],['synthesize','verify'],['verify','publish']])await jobs.completeResearchStep(pub.id,pubClaim.token,stage,{},next);
  await edit('publish',{...brief,parsed:{category:'Home'},nextCheckAt:new Date(Date.now()+86400000).toISOString()},'ready');
  await jobs.finishResearchJob(pub.id,pubClaim.token);assert.equal((await jobs.getResearchJob('publish','owner')).status,'completed');assert.equal((await jobs.ensureResearchJob('publish','owner')).id,pub.id);assert.equal(await jobs.claimResearchJob(pub.id),null);
  await insert('cancel');const cancel=await jobs.ensureResearchJob('cancel','owner');const cancelClaim=await jobs.claimResearchJob(cancel.id);await jobs.cancelResearchJob('cancel','owner');await assert.rejects(jobs.reserveResearchCall(cancel.id,cancelClaim.token),/lease/);assert.equal((await jobs.getResearchJob('cancel','owner')).status,'cancelled');
  // Original-page read checkpoints append by round and survive release/reclaim.
  const privateBody='PRIVATE-CHECKPOINT-CANARY';
  await insert('read-checkpoints');const readJob=await jobs.ensureResearchJob('read-checkpoints','owner'),readClaim=await jobs.claimResearchJob(readJob.id);
  const initialRead={round:0,sources:[{url:'https://example.com/product',accessStatus:'read',bodyText:privateBody,contentHash:'PRIVATE-HASH-CANARY',textTrust:'untrusted-original-page'},
    {url:'https://example.com/provider-listing',accessStatus:'read',bodyText:privateBody,contentHash:'PRIVATE-HASH-CANARY',textTrust:'untrusted-provider-api-json'},
    {url:'https://example.com/provider-extraction',accessStatus:'read',bodyText:privateBody,contentHash:'PRIVATE-HASH-CANARY',textTrust:'untrusted-provider-page'}]};
  const followupRead={round:1,sources:[{url:'https://example.com/compatibility',accessStatus:'blocked',bodyText:'',rawError:privateBody}]};
  await jobs.completeResearchStep(readJob.id,readClaim.token,'plan',{criteria:['Compatible kit']},'gather');
  await jobs.completeResearchStep(readJob.id,readClaim.token,'gather',{sources:[{url:'https://example.com/product'}]},'read');
  await jobs.completeResearchStep(readJob.id,readClaim.token,'read',initialRead,'assess');
  await jobs.completeResearchStep(readJob.id,readClaim.token,'read',initialRead,'assess');
  await jobs.completeResearchStep(readJob.id,readClaim.token,'assess',{gaps:['Accessory compatibility']},'followup');
  await jobs.completeResearchStep(readJob.id,readClaim.token,'followup',{round:1,sources:[{url:'https://example.com/compatibility'}]},'read');
  await jobs.completeResearchStep(readJob.id,readClaim.token,'read',followupRead,'assess');
  await jobs.releaseResearchJob(readJob.id,readClaim.token);
  const readReclaimed=await jobs.claimResearchJob(readJob.id);
  assert.deepEqual(readReclaimed.job.outputs.read,[initialRead,followupRead]);assert.equal(readReclaimed.job.rounds,1);
  const storedRead=(await client.execute({sql:'SELECT payload FROM research_jobs WHERE id=?',args:[readJob.id]})).rows[0];
  assert.deepEqual(JSON.parse(storedRead.payload).outputs.read,[initialRead,followupRead]);
  const publicRead=await jobs.getResearchJob('read-checkpoints','owner');
  assert.equal(publicRead.coverage.sourceCount,2);assert.equal(publicRead.coverage.readCount,1,'A Bright Data field projection or provider extraction is not an independently read original page');
  assert.equal(publicRead.coverage.providerReadCount,2,'Readable provider JSON and page extractions are counted separately');
  assert.equal(publicRead.coverage.blockedCount,1,'Readable provider evidence must not be counted as blocked');
  assert.equal(JSON.stringify(publicRead).includes(privateBody),false);assert.equal(JSON.stringify(publicRead).includes('PRIVATE-HASH-CANARY'),false);
  // Budget validation uses the actual request estimate, retaining reservation accounting and lease fencing.
  process.env.RESEARCH_MAX_INPUT_TOKENS='50';await insert('input-budget');const inputJob=await jobs.ensureResearchJob('input-budget','owner');delete process.env.RESEARCH_MAX_INPUT_TOKENS;
  const inputClaim=await jobs.claimResearchJob(inputJob.id);await jobs.reserveResearchCall(inputJob.id,inputClaim.token);
  await jobs.completeResearchStep(inputJob.id,inputClaim.token,'plan',{criteria:['Budget'],privateProviderBody:privateBody.repeat(100)},'gather','private diagnostic',{inputTokens:10,outputTokens:0});
  const savedInfo=console.info,savedError=console.error,diagnostics=[];
  try {
    console.info=(...args)=>diagnostics.push(args);console.error=(...args)=>diagnostics.push(args);
    const smallEstimate=Math.ceil(JSON.stringify({query:'check exact model'}).length/4);
    const accepted=await jobs.checkResearchInputBudget(inputJob.id,inputClaim.token,smallEstimate);
    assert.equal(accepted.attemptedCalls,1);assert.equal(accepted.inputTokens,10,'A validation must not consume reported usage or count another request');
    const oversizedEstimate=Math.ceil(JSON.stringify({query:'check exact model',page:privateBody.repeat(100)}).length/4);
    await assert.rejects(jobs.checkResearchInputBudget(inputJob.id,inputClaim.token,oversizedEstimate),failure=>failure.code==='budget_exhausted');
    const persistedInput=JSON.parse((await client.execute({sql:'SELECT payload FROM research_jobs WHERE id=?',args:[inputJob.id]})).rows[0].payload);
    assert.equal(persistedInput.attemptedCalls,1);assert.equal(persistedInput.inputTokens,10);
    await assert.rejects(jobs.checkResearchInputBudget(inputJob.id,inputClaim.token,-1),/Invalid/);
    await assert.rejects(jobs.checkResearchInputBudget(inputJob.id,inputClaim.token,1.5),/Invalid/);
    await client.execute({sql:'UPDATE research_jobs SET lease_expires=? WHERE id=?',args:[Date.now()-1,inputJob.id]});
    await assert.rejects(jobs.checkResearchInputBudget(inputJob.id,inputClaim.token,smallEstimate),failure=>failure.code==='lease_lost');
    const freshInput=await jobs.claimResearchJob(inputJob.id);assert.notEqual(freshInput.token,inputClaim.token);
    await assert.rejects(jobs.checkResearchInputBudget(inputJob.id,inputClaim.token,smallEstimate),failure=>failure.code==='lease_lost');
    assert.equal((await jobs.checkResearchInputBudget(inputJob.id,freshInput.token,smallEstimate)).attemptedCalls,1);
    assert.equal(JSON.stringify(diagnostics).includes(privateBody),false);assert.equal(JSON.stringify(diagnostics).includes('private diagnostic'),false);
  } finally {console.info=savedInfo;console.error=savedError;}
  // Tool attempts persist before dispatch, including failures, retries and competing callbacks.
  process.env.RESEARCH_MAX_TOOL_CALLS='2';await insert('tool-budget');const toolJob=await jobs.ensureResearchJob('tool-budget','owner');delete process.env.RESEARCH_MAX_TOOL_CALLS;
  const toolClaim=await jobs.claimResearchJob(toolJob.id);
  await Promise.all([jobs.reserveResearchToolCall(toolJob.id,toolClaim.token),jobs.reserveResearchToolCall(toolJob.id,toolClaim.token)]);
  await assert.rejects(jobs.reserveResearchToolCall(toolJob.id,toolClaim.token),error=>error.code==='budget_exhausted');
  await jobs.failResearchJob(toolJob.id,toolClaim.token,'PRIVATE-TOOL-FAILURE',{retryable:true});await jobs.retryResearchJob('tool-budget','owner');
  const toolRetry=await jobs.claimResearchJob(toolJob.id);assert.equal(toolRetry.job.attemptedToolCalls,2);assert.equal(toolRetry.job.attemptedCalls,0);
  await assert.rejects(jobs.reserveResearchToolCall(toolJob.id,toolRetry.token),error=>error.code==='budget_exhausted');
  assert.equal((await jobs.getResearchJob('tool-budget','owner')).limits.maxToolCalls,2);
  await client.execute({sql:'UPDATE research_jobs SET lease_expires=? WHERE id=?',args:[Date.now()-1,toolJob.id]});
  await assert.rejects(jobs.reserveResearchToolCall(toolJob.id,toolRetry.token),error=>error.code==='lease_lost');
  const toolReclaimed=await jobs.claimResearchJob(toolJob.id);await jobs.cancelResearchJob('tool-budget','owner');
  await assert.rejects(jobs.reserveResearchToolCall(toolJob.id,toolReclaimed.token),error=>error.code==='lease_lost');
  process.env.RESEARCH_MAX_TOOL_CALLS='999';await insert('tool-hard-cap');const toolHard=await jobs.ensureResearchJob('tool-hard-cap','owner');delete process.env.RESEARCH_MAX_TOOL_CALLS;assert.equal(toolHard.limits.maxToolCalls,24);
  // Legacy payloads acquire default tool accounting without changing saved model limits.
  const legacyPayload=JSON.parse((await client.execute({sql:'SELECT payload FROM research_jobs WHERE id=?',args:[toolHard.id]})).rows[0].payload);delete legacyPayload.attemptedToolCalls;delete legacyPayload.limits.maxToolCalls;
  await client.execute({sql:'UPDATE research_jobs SET payload=? WHERE id=?',args:[JSON.stringify(legacyPayload),toolHard.id]});
  const legacyClaim=await jobs.claimResearchJob(toolHard.id);assert.equal(legacyClaim.job.limits.maxToolCalls,12);assert.equal(legacyClaim.job.attemptedToolCalls,0);assert.equal(legacyClaim.job.limits.maxCalls,8);
  // Extra SDK generations leave durable call/output room for assessment and synthesis.
  await insert('model-reserve');const modelJob=await jobs.ensureResearchJob('model-reserve','owner'),modelClaim=await jobs.claimResearchJob(modelJob.id);
  for(let i=0;i<5;i++)await jobs.reserveResearchCall(modelJob.id,modelClaim.token);
  await jobs.checkResearchModelBudget(modelJob.id,modelClaim.token,{inputTokens:20,maxOutputTokens:6000,reserveCalls:2,reserveOutputTokens:6000});
  await jobs.reserveResearchCall(modelJob.id,modelClaim.token,{inputTokens:40,maxOutputTokens:6000,pendingOutputTokens:6000,reserveCalls:2,reserveOutputTokens:6000});
  await assert.rejects(jobs.reserveResearchCall(modelJob.id,modelClaim.token,{reserveCalls:2}),error=>error.code==='budget_exhausted');
  await assert.rejects(jobs.checkResearchModelBudget(modelJob.id,modelClaim.token,{maxOutputTokens:6000,pendingOutputTokens:19000}),error=>error.code==='budget_exhausted');
  await assert.rejects(jobs.checkResearchModelBudget(modelJob.id,modelClaim.token,{inputTokens:1.5}),/Invalid/);
  assert.equal((await jobs.getResearchJob('model-reserve','owner')).limits.attemptedCalls,6);
  await jobs.reserveResearchCall(modelJob.id,modelClaim.token);await jobs.reserveResearchCall(modelJob.id,modelClaim.token);
  assert.equal((await jobs.getResearchJob('model-reserve','owner')).limits.attemptedCalls,8);
  process.env.NODE_ENV='production';process.env.RESEARCH_USER_DAILY_JOB_LIMIT='1';process.env.RESEARCH_DAILY_JOB_LIMIT='100';
  await insert('production-user-limit');await assert.rejects(jobs.ensureResearchJob('production-user-limit','owner'),error=>error.code==='daily_limit');
  await insert('production-global-limit','new-owner');process.env.RESEARCH_DAILY_JOB_LIMIT='1';
  await assert.rejects(jobs.ensureResearchJob('production-global-limit','new-owner'),error=>error.code==='daily_limit');
  assert.equal((await jobs.ensureResearchJob('model-reserve','owner')).id,modelJob.id,'Existing jobs are idempotent even after a daily cap');
  process.env.NODE_ENV='test';
  await insert('authorized-output-extension');const extensionJob=await jobs.ensureResearchJob('authorized-output-extension','owner');
  let extensionLease=await jobs.claimResearchJob(extensionJob.id);
  await jobs.reserveResearchCall(extensionJob.id,extensionLease.token);
  await jobs.recordResearchUsage(extensionJob.id,extensionLease.token,{inputTokens:11,outputTokens:12});
  await jobs.failResearchJob(extensionJob.id,extensionLease.token,'truncated');
  process.env.RESEARCH_RETRY_JOB_ID='a-different-job';process.env.RESEARCH_RETRY_OUTPUT_BUDGET='131072';
  await jobs.retryResearchJob('authorized-output-extension','owner');
  extensionLease=await jobs.claimResearchJob(extensionJob.id);assert.equal(extensionLease.job.limits.maxOutputTokens,extensionJob.limits.maxOutputTokens);
  await jobs.failResearchJob(extensionJob.id,extensionLease.token,'truncated');
  process.env.RESEARCH_RETRY_JOB_ID=extensionJob.id;
  await jobs.retryResearchJob('authorized-output-extension','owner');
  extensionLease=await jobs.claimResearchJob(extensionJob.id);
  assert.equal(extensionLease.job.limits.maxOutputTokens,131072);
  assert.equal(extensionLease.job.attemptedCalls,1);assert.equal(extensionLease.job.outputTokens,12);assert.equal(extensionLease.job.inputTokens,11);
  delete process.env.RESEARCH_RETRY_JOB_ID;delete process.env.RESEARCH_RETRY_OUTPUT_BUDGET;
  console.log('PASS: durable bounded jobs, tool/model attempt budgets across retries, legacy defaults and hard cap, final-call reserve, ownership, checkpoint journals, input checks and lease/cancellation fencing');
} finally {client?.close();await rm(directory,{recursive:true,force:true});for(const [key,value] of Object.entries(saved)){if(value===undefined)delete process.env[key];else process.env[key]=value;}}
