import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {registerHooks} from 'node:module';
registerHooks({resolve(s,c,next){try{return next(s,c);}catch(e){if(s.startsWith('.'))return next(`${s}.ts`,c);throw e;}}});
const {CLAIM_ASSESSMENT_SCHEMA,validateClaimAssessment,applyClaimLedger,ambiguousExactVariant,requiredPlanCriteria}=await import('../lib/research/claims.ts');
const date='2026-10-08T10:00:00Z',url='https://www.amazon.in/dp/book14',penUrl='https://www.amazon.in/dp/pen2',reviewUrl='https://www.rtings.com/laptop/reviews/acme-book14';
const title='Acme Book14 16GB RAM 512GB SSD';
const productQuote='Acme Book14 16GB RAM 512GB SSD. New condition. In stock. Item price INR 45000. Compatible with Acme Pen2.';
const compatibilityQuote='Acme Book14 16GB RAM 512GB SSD supports the pressure-sensitive Acme Pen2.';
const penQuote='Acme Pen2 compatible stylus. New condition. In stock. Price INR 5000.';
const measured='Lab test: Acme Book14 16GB RAM 512GB SSD measured battery 8 hours at 50% brightness with a browser workload.';
function source(url,title,bodyText,sourceKind='retailer'){return {url,title,bodyText,sourceKind,accessStatus:'read',retrievedAt:date,publishedAt:null,contentHash:createHash('sha256').update(bodyText).digest('hex'),textTrust:'untrusted-original-page',paragraphs:[bodyText],quotes:[{text:bodyText,start:0,end:bodyText.length}]};}
const sources=[source(url,title,`${productQuote}\n\n${compatibilityQuote}`),source(penUrl,'Acme Pen2',penQuote),source(reviewUrl,title,measured,'review')];
const proof=(sourceUrl,quote)=>({sourceUrl,quote});
const candidate={name:'Acme Book14',variant:'16GB RAM 512GB SSD',hardRequirements:[{requirement:'16GB',status:'supported',...proof(url,productQuote)}],
  comparisonClaims:[{text:'Measured battery 8 hours',kind:'measurement',...proof(reviewUrl,measured)}],
  mandatoryAccessories:[{name:'Acme Pen2',requirement:'Acme Pen2',required:true,compatibility:{status:'supported',...proof(url,compatibilityQuote)},price:{value:5000,...proof(penUrl,penQuote)}}],
  productPrice:{value:45000,...proof(url,productQuote)},condition:{value:'new',...proof(url,productQuote)},currentAvailability:{value:'in_stock',...proof(url,productQuote)}};
const raw={gaps:[],followupQuestions:[],sufficient:true,candidates:[candidate]};
const context={brief:{requestText:'Must have 16GB RAM. Only new.',country:'India',condition:'New only',budget:55000,topN:3},plan:{hardRequirements:['16GB'],softPreferences:['Quiet fan'],requiredAccessories:['Acme Pen2']},referenceDate:date,sources};
const validate=(item=candidate,overrides={})=>validateClaimAssessment({...raw,candidates:[item]},{...context,...overrides});
const ledger=validate(),accepted=ledger.candidates[0];
assert.equal(accepted.eligibility.blocked,false);assert.equal(accepted.eligibility.provisional,false);
assert.equal(accepted.eligibility.completeKitCost,50000);assert.equal(accepted.eligibility.checkoutVerified,false);
assert.equal(accepted.hardRequirements[0].status,'supported');assert.equal(accepted.comparisonClaims[0].status,'supported');
for(const requirement of ['New product only','India-market product listing','Required item and accessory subtotal at most INR 55000'])assert.equal(accepted.hardRequirements.find(c=>c.requirement===requirement).status,'supported');
assert.equal(ambiguousExactVariant('8GB RAM and 256GB storage'),false);
const functional=validate({...candidate,mandatoryAccessories:[{...candidate.mandatoryAccessories[0],requirement:'Compatible pressure-sensitive stylus'}]},{plan:{...context.plan,requiredAccessories:['Compatible pressure-sensitive stylus'],conditionalAccessories:['Pairing adapter if needed']}}).candidates[0];assert.equal(functional.mandatoryAccessories.length,1,'An exact compatible pen covers the functional role without a duplicate generic accessory');
const optional=validate({...candidate,mandatoryAccessories:[{...candidate.mandatoryAccessories[0],required:false}]}).candidates[0];assert.equal(optional.eligibility.provisional,true,'An optional accessory cannot satisfy a mandatory slot');
assert.equal(ambiguousExactVariant('128GB / 256GB storage'),true);
assert.equal(validate({...candidate,variant:'128GB / 256GB storage'}).candidates[0].eligibility.blocked,true);
const warranty='Acme Book14 16GB RAM 512GB SSD. One year manufacturer warranty for the device and accessories.';
for(const requirement of ['Condition must be brand new (no refurbished units)','Pressure-sensitive pen with palm rejection']){
 const unsupported=validate({...candidate,hardRequirements:[{requirement,status:'supported',...proof(url,warranty)}]},{sources:[source(url,title,warranty),...sources.slice(1)],plan:{...context.plan,hardRequirements:[requirement]}}).candidates[0];
 assert.equal(unsupported.hardRequirements.find(c=>c.requirement===requirement).status,'unknown','Warranty text does not establish new condition, pressure or palm rejection');
}
const noCardAssumption='Base price must not assume unverified SBI credit/debit/EMI card promotions';
assert.equal(validate({...candidate,hardRequirements:[{requirement:noCardAssumption,status:'supported',...proof(url,'₹45,000')}]},{sources:[source(url,title,title+'\n₹45,000'),...sources.slice(1)],plan:{...context.plan,hardRequirements:[noCardAssumption]}}).candidates[0].hardRequirements[0].status,'unknown');
const flipkartUrl='https://www.flipkart.com/acme-book14/p/example';
const flipkartPrice=validate({...candidate,productPrice:{value:45000,...proof(flipkartUrl,'₹45,000')}},{sources:[source(flipkartUrl,title,title+'\n₹45,000'),...sources.slice(1)]}).candidates[0];
assert.equal(flipkartPrice.productPrice,45000,'The www Flipkart host is the same India market as its apex');
assert.equal(flipkartPrice.hardRequirements.find(c=>c.requirement==='India-market product listing').status,'supported');
const display='Acme Book14 16GB RAM 512GB SSD has a 10.9-inch display.';
const displayCandidate={...candidate,hardRequirements:[{requirement:'Display size between 10.0 and 11.0 inches',status:'supported',...proof(url,display)}]};
assert.equal(validate(displayCandidate,{sources:[source(url,title,display),...sources.slice(1)],plan:{...context.plan,hardRequirements:[displayCandidate.hardRequirements[0].requirement]}}).candidates[0].hardRequirements[0].status,'supported');
const priceBody=title+'\n\n₹45,000\n\nRelated products: ₹19,999';
assert.equal(validate({...candidate,productPrice:{value:45000,...proof(url,'₹45,000')}},{sources:[source(url,title,priceBody),...sources.slice(1)]}).candidates[0].productPrice,45000,'Short atomic prices from an exact SKU page are valid quotes');
assert.equal(validate({...candidate,productPrice:{value:19999,...proof(url,'₹19,999')}},{sources:[source(url,title,priceBody),...sources.slice(1)]}).candidates[0].productPrice,null,'Do not select a later carousel or conditional amount as an atomic price');
const wrongQuote=validate({...candidate,hardRequirements:[{requirement:'16GB',status:'supported',...proof(url,'Acme Book14 16GB RAM 512GB SSD has zero-latency battery life.')}]}).candidates[0];
assert.equal(wrongQuote.hardRequirements[0].status,'unknown');assert.equal(wrongQuote.eligibility.provisional,true);
const groundedOnly=validate(candidate,{sources:sources.map(s=>({...s,accessStatus:'unsupported',bodyText:'',contentHash:null,excerpts:[productQuote,measured,penQuote]}))}).candidates[0];
assert.equal(groundedOnly.hardRequirements[0].status,'unknown');assert.equal(groundedOnly.productPrice,null);
assert.equal(validate(candidate,{sources:sources.map(s=>({...s,contentHash:'a'.repeat(64)}))}).candidates[0].productPrice,null);
assert.equal(validate(candidate,{sources:sources.map(s=>({...s,retrievedAt:'2027-01-01T00:00:00Z'}))}).candidates[0].productPrice,null);
const past=validate(candidate,{sources:sources.map(s=>({...s,retrievedAt:'2026-10-01T00:00:00Z'}))}).candidates[0];
assert.equal(past.productPrice,null,'An old snapshot cannot establish a current price');
const historicalPrice='Acme Book14 16GB RAM 512GB SSD. Sale price INR 45000 as of October 2024. New condition. In stock.';
assert.equal(validate({...candidate,productPrice:{value:45000,...proof(url,historicalPrice)}},{sources:[source(url,title,historicalPrice),...sources.slice(1)]}).candidates[0].productPrice,null,'A freshly read page cannot make an explicitly old sale price current');
const conditionalPrice='Acme Book14 16GB RAM 512GB SSD. New condition. In stock. Item price INR 45000 with an SBI credit card.';
assert.equal(validate({...candidate,productPrice:{value:45000,...proof(url,conditionalPrice)}},{sources:[source(url,title,conditionalPrice),...sources.slice(1)]}).candidates[0].productPrice,null,'Conditional card price is not an unconditional budget subtotal');
const generation=validate({...candidate,hardRequirements:[{requirement:'Current generation',status:'supported',...proof(url,productQuote)}]},{plan:{...context.plan,hardRequirements:['Current generation']}}).candidates[0];
assert.equal(generation.hardRequirements.find(c=>c.requirement==='Current generation').status,'unknown');
const missingCost=validate({...candidate,mandatoryAccessories:[{...candidate.mandatoryAccessories[0],price:{value:null,sourceUrl:'',quote:''}}]}).candidates[0];
assert.equal(missingCost.eligibility.completeKitCost,null);assert.equal(missingCost.eligibility.provisional,true);
assert.equal(validate(candidate,{brief:{...context.brief,budget:49000}}).candidates[0].eligibility.blocked,true);
const incompatible='Acme Book14 16GB RAM 512GB SSD is incompatible with Acme Pen2.';
const incompatibleSource=source(url,title,`${productQuote}\n\n${incompatible}`);
const incompatibleCandidate={...candidate,mandatoryAccessories:[{...candidate.mandatoryAccessories[0],compatibility:{status:'contradicted',...proof(url,incompatible)}}]};
assert.equal(validate(incompatibleCandidate,{sources:[incompatibleSource,...sources.slice(1)]}).candidates[0].eligibility.blocked,true);
const nonPressure='Acme Book14 16GB RAM 512GB SSD only supports a pen without pressure sensitivity.';
assert.equal(validate({...candidate,hardRequirements:[{requirement:'Pressure-sensitive pen',status:'contradicted',...proof(url,nonPressure)}]},{sources:[source(url,title,nonPressure),...sources.slice(1)]}).candidates[0].eligibility.blocked,true);
assert.equal(validate({...candidate,hardRequirements:[{requirement:'Pressure-sensitive pen',status:'supported',...proof(url,nonPressure)}]},{sources:[source(url,title,nonPressure),...sources.slice(1)]}).candidates[0].eligibility.blocked,true,'Clear pressure negation overrides an incorrect supported label');
const foreignUrl='https://www.apple.com/us/shop/acme-book14',foreignQuote=productQuote.replace('INR','USD');
assert.equal(validate({...candidate,productPrice:{value:45000,...proof(foreignUrl,foreignQuote)}},{sources:[...sources,source(foreignUrl,title,foreignQuote,'official')]}).candidates[0].eligibility.blocked,true);
const refurbished='Acme Book14 16GB RAM 512GB SSD. Condition: refurbished. In stock. Item price INR 45000.';
assert.equal(validate({...candidate,condition:{value:'new',...proof(url,refurbished)}},{sources:[source(url,title,`${refurbished}\n\n${compatibilityQuote}`),...sources.slice(1)]}).candidates[0].eligibility.blocked,true);
const unavailable='Acme Book14 16GB RAM 512GB SSD. New condition. Out of stock. Item price INR 45000.';
assert.equal(validate({...candidate,currentAvailability:{value:'in_stock',...proof(url,unavailable)}},{sources:[source(url,title,unavailable),...sources.slice(1)]}).candidates[0].eligibility.blocked,true);
const badMeasurement=validate({...candidate,comparisonClaims:[{text:'Measured battery 19 hours',kind:'measurement',...proof(reviewUrl,measured)}]}).candidates[0];
assert.equal(badMeasurement.comparisonClaims[0].status,'unknown');
assert.equal(validate({...candidate,comparisonClaims:[{text:'Underwater camera is included',kind:'specification',...proof(url,productQuote)}]}).candidates[0].comparisonClaims[0].status,'unknown','A real quote must not support an unrelated invented claim');
const retailerMeasurement=validate({...candidate,comparisonClaims:[{text:'Measured battery 8 hours',kind:'measurement',...proof(url,measured)}]},{sources:[source(url,title,`${productQuote}\n\n${measured}\n\n${compatibilityQuote}`),...sources.slice(1)]}).candidates[0];
assert.equal(retailerMeasurement.comparisonClaims[0].status,'unknown');
const ownerUrl='https://www.reddit.com/r/laptops/comments/example',owner=source(ownerUrl,title,measured,'owner');
const ownerMeasurement=validate({...candidate,comparisonClaims:[{text:'Measured battery 8 hours',kind:'measurement',...proof(ownerUrl,measured)}]},{sources:[...sources,owner]}).candidates[0];
assert.equal(ownerMeasurement.comparisonClaims[0].kind,'anecdote');assert.equal(ownerMeasurement.comparisonClaims[0].status,'unknown');
const ownerAnecdote=validate({...candidate,comparisonClaims:[{text:'Battery 8 hours',kind:'anecdote',...proof(ownerUrl,measured)}]},{sources:[...sources,owner]}).candidates[0];
assert.equal(ownerAnecdote.comparisonClaims[0].status,'supported');
const crossProduct='Acme OtherBook 8GB RAM 256GB SSD. New condition. In stock. Item price INR 45000.';
const contaminated=validate({...candidate,productPrice:{value:45000,...proof(url,crossProduct)}},{sources:[source(url,title,`${productQuote}\n\nRecommended product: ${crossProduct}`),...sources.slice(1)]}).candidates[0];
assert.equal(contaminated.productPrice,null,'Exact title cannot make another SKU carousel quote relevant');
const sameMemoryDifferentModel='Acme Book15 16GB RAM 512GB SSD. New condition. In stock. Item price INR 45000.';
assert.equal(validate({...candidate,productPrice:{value:45000,...proof(url,sameMemoryDifferentModel)}},{sources:[source(url,title,`${productQuote}\n\n${sameMemoryDifferentModel}`),...sources.slice(1)]}).candidates[0].productPrice,null,'A different model sharing RAM/storage is still another SKU');
const generatedIdentity='Other product price INR 45000';
assert.equal(validate({...candidate,productPrice:{value:45000,...proof(url,generatedIdentity)}},{sources:[source(url,'Acme family',`${title}\n${generatedIdentity}`),...sources.slice(1)]}).candidates[0].productPrice,null,'Identity elsewhere in full body is insufficient');
const notCovered=validate({...candidate,hardRequirements:[]}).candidates[0];
assert.equal(notCovered.hardRequirements.find(c=>c.requirement==='16GB').status,'unknown');
assert.equal(notCovered.eligibility.provisional,true);
assert.equal(requiredPlanCriteria(context.brief,context.plan).includes('Quiet fan'),false,'Soft ranking preferences are not hard filters');
const emptyPlan=validate(candidate,{plan:{hardRequirements:[],softPreferences:['Quiet fan'],requiredAccessories:[]}}).candidates[0];
assert.equal(emptyPlan.eligibility.provisional,true,'Explicit must/only text cannot disappear through an empty model plan');
const whitespace=validate({...candidate,productPrice:{value:45000,...proof(url,productQuote.replace(/ /g,'  '))}}).candidates[0];
assert.equal(whitespace.productPrice,45000);const located=whitespace.productPriceEvidence;
assert.equal(sources[0].bodyText.slice(located.start,located.end),located.quote);assert.equal(located.contentHash,sources[0].contentHash);
const draft={summary:'Comparison',products:[{name:candidate.name,variant:candidate.variant,pros:['Measured battery 8 hours','Unsupported zero latency'],cons:[],sources:[],offers:[]}],excluded:[],needsClarification:['Which app must be supported?']};
const published=applyClaimLedger(draft,ledger,context.brief);
assert.deepEqual(published.products[0].pros,['Measured battery 8 hours']);assert.equal(published.products[0].claimEvidence.checkoutVerified,false);
assert.equal(JSON.stringify(published).includes(productQuote),false);assert.equal(JSON.stringify(published).includes(measured),false);
assert.equal(published.products[0].claimEvidence.sourceRefs[0].contentHash.length,64);
const provisional=applyClaimLedger(draft,validate({...candidate,hardRequirements:[]}),context.brief);
assert.deepEqual(provisional.needsClarification,['Which app must be supported?']);assert.ok(provisional.researchGaps.some(gap=>gap.includes('16GB')));
assert.equal(applyClaimLedger(draft,validate(candidate,{brief:{...context.brief,budget:49000}}),context.brief).products.length,0);
const onlyMarketEvidence=validate({...candidate,hardRequirements:[],comparisonClaims:[]});
assert.equal(applyClaimLedger(draft,onlyMarketEvidence,context.brief).products.length,0,'Market/condition/budget evidence alone cannot establish suitability or a #1 pick');
const noProof=validate(candidate,{sources:[]});assert.equal(applyClaimLedger(draft,noProof,context.brief).products.length,0,'All-unknown leads must not become #1 recommendations');
assert.equal(applyClaimLedger({...draft,products:[...draft.products,...draft.products]},ledger,{...context.brief,topN:1}).products.length,1);

const unverifiedBundle=applyClaimLedger({...draft,products:[{...draft.products[0],offers:[{url,accessories:'Includes free Acme Pen2',verified:true,total:50000}]}]},ledger,context.brief).products[0].offers[0];
assert.doesNotMatch(unverifiedBundle.accessories,/Includes free/);
assert.equal(unverifiedBundle.total,null);assert.equal(unverifiedBundle.mandatoryCostsVerified,false);
function strict(schema){if(schema.type==='object'){assert.equal(schema.additionalProperties,false);assert.deepEqual(schema.required,Object.keys(schema.properties));Object.values(schema.properties).forEach(strict);}if(schema.type==='array')strict(schema.items);}
strict(CLAIM_ASSESSMENT_SCHEMA);
assert.deepEqual(validateClaimAssessment({candidates:[null]},{...context,sources:[]}).candidates,[]);
console.log('PASS: original-page quote/hash/SKU evidence, hard/soft constraints, accessory budget, condition/stock/date, measurement vs anecdote, contamination rejection and quote-free publication');
