import {verifierConfigured} from './research/offer-verifier';
import {starter} from './seed';
import {database} from './database';
export const db=()=>database;
const emptyProfile={country:'India',currency:'INR',postcode:'',banks:'',condition:'New only',priorities:[]};
export function schedulerMinIntervalHours(){const n=Number(process.env.WORKER_MIN_INTERVAL_HOURS||24);return Number.isInteger(n)&&n>=1&&n<=24?n:24;}
export function researchReady(){return !!process.env.OPENAI_API_KEY&&!!process.env.CRON_SECRET&&process.env.CRON_SECRET.length>=32;}
export async function initialize(userId:string){
  await db().prepare('INSERT OR IGNORE INTO workspace (id,settings) VALUES (?,?)').bind(userId,JSON.stringify({profile:emptyProfile,schedule:'pending'})).run();
  if(process.env.NODE_ENV!=='production'&&process.env.MIRANA_DEMO_MODE==='true'&&userId==='local-demo'){
    await db().prepare('INSERT OR IGNORE INTO purchases (id,user_id,brief,report,status,updated_at) SELECT ?,?,?,?,?,? WHERE NOT EXISTS (SELECT 1 FROM purchases WHERE user_id=?)').bind('local-demo-tablet',userId,JSON.stringify({...starter,requestText:starter.usage,topN:3,productUrl:'',alerts:{enabled:false,mode:'interval',intervalHours:24,rule:'history',targetPrice:null},parsed:null}),null,'queued',new Date().toISOString(),userId).run();
  }
}
export async function readWorkspace(userId:string){await initialize(userId);const [p,s,o,global]=await Promise.all([db().prepare('SELECT * FROM purchases WHERE user_id=? ORDER BY updated_at DESC').bind(userId).all(),db().prepare('SELECT settings FROM workspace WHERE id=?').bind(userId).first(),db().prepare('SELECT o.purchase_id,o.payload FROM observations o JOIN purchases p ON p.id=o.purchase_id WHERE p.user_id=?').bind(userId).all(),db().prepare('SELECT settings FROM workspace WHERE id=?').bind('system').first()]);return {purchases:p.results.map((r:any)=>({...JSON.parse(r.brief),id:r.id,report:r.report?JSON.parse(r.report):null,status:r.status,updatedAt:r.updated_at})),settings:{...JSON.parse((s as any).settings),...(global?JSON.parse((global as any).settings):{}),researchReady:researchReady(),offerVerificationReady:verifierConfigured(),schedulerMinIntervalHours:schedulerMinIntervalHours()},observations:o.results.map((r:any)=>({...JSON.parse(r.payload),purchaseId:r.purchase_id}))};}
export function guard(request:Request){const origin=request.headers.get('origin');const fetchSite=request.headers.get('sec-fetch-site');if((origin&&origin!==new URL(request.url).origin)||fetchSite==='cross-site')throw new Error('Cross-site writes are not allowed.');}
export async function body(request:Request){guard(request);if(!request.headers.get('content-type')?.includes('application/json'))throw new Error('Send JSON.');const raw=await request.text();if(raw.length>300000)throw new Error('Request is too large.');return JSON.parse(raw);}
export const fail=(e:unknown)=>Response.json({error:e instanceof Error?e.message:'Request failed.'},{status:400});
const clean=(v:any,n:number)=>typeof v==='string'?v.trim().slice(0,n):'';
export function alerts(a:any={}){const intervalHours=Number(a.intervalHours||24);if(!Number.isInteger(intervalHours)||intervalHours<1||intervalHours>168)throw new Error('Check frequency must be 1–168 hours.');const mode=a.mode==='daily'?'daily':'interval';if(mode==='interval'&&intervalHours<schedulerMinIntervalHours())throw new Error(`The configured scheduler supports intervals of ${schedulerMinIntervalHours()} hours or longer.`);const dailyHour=Number(a.dailyHour??10);if(!Number.isInteger(dailyHour)||dailyHour<0||dailyHour>23)throw new Error('Choose a valid daily hour.');const rule=a.rule==='target'?'target':'history';const targetPrice=a.targetPrice?Number(a.targetPrice):null;if(rule==='target'&&(!targetPrice||targetPrice<1||targetPrice>10000000))throw new Error('Enter a valid target price.');return {enabled:a.enabled===true,mode,intervalHours,dailyHour,rule,targetPrice};}
export function validUrl(v:any){if(typeof v!=='string')return false;try{const u=new URL(v);return u.protocol==='https:'&&!u.username&&!u.password&&!u.port&&u.hostname.includes('.')&&!/^(localhost|127\.|0\.|10\.|192\.168\.|169\.254\.|172\.(1[6-9]|2\d|3[01])\.)/.test(u.hostname)&&!u.hostname.endsWith('.local')}catch{return false}}
export function brief(d:any,profile:any){const requestText=clean(d.requestText,6000);const productUrl=clean(d.productUrl,2000);if(requestText.length<5&&!productUrl)throw new Error('Describe what you want or add a product link.');if(productUrl&&!validUrl(productUrl))throw new Error('Use a public HTTPS product link.');const topMatch=requestText.match(/top\s*(\d+)/i);const topN=Number(d.topN||topMatch?.[1]||3);if(!Number.isInteger(topN)||topN<1||topN>20)throw new Error('Choose 1–20 recommendations.');const budgetMatch=requestText.match(/(?:₹|rs\.?\s*|inr\s*)(\d[\d,]*(?:\.\d+)?)\s*(k|lakh)?/i);const inferred=budgetMatch?Number(budgetMatch[1].replace(/,/g,''))*(budgetMatch[2]?.toLowerCase()==='k'?1000:budgetMatch[2]?.toLowerCase()==='lakh'?100000:1):null;const budget=d.budget?Number(d.budget):inferred;if(budget!==null&&(!Number.isFinite(budget)||budget<1||budget>10000000))throw new Error('Enter a valid budget.');const postcode=clean(d.postcode||profile.postcode,6);if(!/^\d{6}$/.test(postcode))throw new Error('Enter a six-digit Indian postcode.');const categories=[['Tablet',/tablet|ipad|galaxy tab/i],['Laptop',/laptop|macbook|notebook computer/i],['Phone',/phone|iphone|smartphone/i],['Audio',/headphone|earbud|speaker|audio/i],['Camera',/camera|lens/i],['Home',/fridge|refrigerator|washing machine|vacuum|furniture|mattress|kitchen|coffee/i],['Fitness',/fitness|treadmill|cycle|sports/i]] as const;const category=categories.find(([,re])=>re.test(requestText))?.[0]||'Product';return {title:clean(d.title,100)||`${category} search`,requestText,usage:requestText,productUrl,topN,budget,category,size:'',priorities:profile.priorities||[],condition:'New only',banks:clean(d.banks||profile.banks,200),postcode,country:'India',currency:'INR',alerts:alerts(d.alerts),parsed:null};}
export function validateReport(r:any,topN=3){if(!r||typeof r.summary!=='string'||!Array.isArray(r.products)||r.products.length>topN)throw new Error('A report needs a summary and no more than the requested top N products.');if(!r.checkedAt||!Number.isFinite(Date.parse(r.checkedAt)))throw new Error('Report needs a valid checkedAt timestamp.');if(r.products.length&&r.recommendedId!==r.products[0].id)throw new Error('The #1 recommendation must be the first ranked product.');for(const p of r.products){if(!p.id||!p.name||!Array.isArray(p.pros)||!Array.isArray(p.cons)||!Array.isArray(p.sources)||!Array.isArray(p.offers))throw new Error('Incomplete product evidence.');for(const s of [...p.sources,...p.offers])if(!validUrl(s.url))throw new Error('Evidence links must be public HTTPS.');for(const o of p.offers){if(!Number.isFinite(Date.parse(o.checkedAt)))throw new Error('Offers need a checkedAt timestamp.');if(o.price!==null&&(!Number.isFinite(o.price)||o.price<0))throw new Error('Invalid price.');if(o.total!==null&&o.total!==undefined&&(!Number.isFinite(o.total)||o.total<0))throw new Error('Invalid total.');}}return r;}
